version: "3"


services:
  backend:
    container_name: backend
    build:
      context: "./"
      dockerfile: Dockerfile

    environment:
      DATABASE_URL: "file:./dev.db"

    volumes:
      - .:/app
    
    ports:
      - 3000:3000
